name: example
description: An example application for the package.

environment:
  sdk: '>=3.8.0'

dependencies:
  grpc: ^4.0.0
  protobuf: ^3.1.0

dev_dependencies:
  build_runner: ^2.7.0
  lints: ^6.0.0
  protoc_builder:
    path: ../

